/*  This file is part of the CodeDiff code diffing tool.
 *
 *  Copyright (C) 2026 Marko Ivankovic
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
#[cfg(test)]
mod c_cpython_autogenerated_code;
#[cfg(test)]
mod c_ffmpeg_added_typedef_to_enum;
#[cfg(test)]
mod c_freeciv_add_parameter_to_function;
#[cfg(test)]
mod c_htop_remove_function_declaration;
#[cfg(test)]
mod c_linux_small_bugfix;
#[cfg(test)]
mod c_linux_small_change;
#[cfg(test)]
mod c_linux_small_change_struct_to_char;
#[cfg(test)]
mod c_microsoft_terminal_add_function;
#[cfg(test)]
mod c_nginx_add_typedef;
#[cfg(test)]
mod c_postgres_real_logic_change;
#[cfg(test)]
mod cpp_godot_small_bugfix;
#[cfg(test)]
mod cpp_ladybird_refactor_variables_if_changes;
#[cfg(test)]
mod cpp_laydbird_change_function_signature;
#[cfg(test)]
mod cpp_libreoffice_add_const;
#[cfg(test)]
mod cpp_libreoffice_remove_return_value;
#[cfg(test)]
mod cpp_nextcloud_add_test_case;
#[cfg(test)]
mod cpp_ollama_add_function_argument;
#[cfg(test)]
mod cpp_opencv_add_test_case;
#[cfg(test)]
mod cpp_tensorflow_switch_to_primitive_types;
#[cfg(test)]
mod cpp_whitespace_only_change;
#[cfg(test)]
mod csharp_jellyfin_add_function;
#[cfg(test)]
mod csharp_jellyfin_sql_query_fix;
#[cfg(test)]
mod csharp_lidarr_add_function;
#[cfg(test)]
mod csharp_lidarr_call_different_function;
#[cfg(test)]
mod csharp_lidarr_condition_change;
#[cfg(test)]
mod csharp_lidarr_new_feature;
#[cfg(test)]
mod csharp_radarr_add_object_instance;
#[cfg(test)]
mod csharp_sonarr_add_if_block;
#[cfg(test)]
mod csharp_sonarr_add_true_to_function_call;
#[cfg(test)]
mod csharp_sonarr_change_type;
#[cfg(test)]
mod css_add_property;
#[cfg(test)]
mod css_playwright_add_class_selector;
#[cfg(test)]
mod css_shadcn_ui_ui_completely_broken_treesitter_parsing;
#[cfg(test)]
mod css_wordpress_add_comment;
#[cfg(test)]
mod css_wordpress_format_comment_and_fix;
#[cfg(test)]
mod css_wordpress_reformat;
#[cfg(test)]
mod css_wordpress_smalll_change;
#[cfg(test)]
mod css_wordpress_wordpress_autogenerated_file;
#[cfg(test)]
mod css_wordpress_wordpress_change_simple_values_to_vars;
#[cfg(test)]
mod go_caddy_rename_type;
#[cfg(test)]
mod go_gin_add_function;
#[cfg(test)]
mod go_gin_change_import;
#[cfg(test)]
mod go_gin_constant_change;
#[cfg(test)]
mod go_lazygit_add_to_if_condition;
#[cfg(test)]
mod go_lazygit_switch_to_strings;
#[cfg(test)]
mod go_ollama_ollama_surround_block_with_if_and_function_call;
#[cfg(test)]
mod go_prometheus_single_comment_change;
#[cfg(test)]
mod go_user_slices_library;
#[cfg(test)]
mod html_fatedier_add_attribute;
#[cfg(test)]
mod html_firefox_update_src;
#[cfg(test)]
mod html_gohugoio_hugo_enclose_table_with_div_and_add_thead_tbody;
#[cfg(test)]
mod html_gorhill_add_tag;
#[cfg(test)]
mod html_hugo_tag_to_selfclosing_tag;
#[cfg(test)]
mod html_ladybird_delete_attribute;
#[cfg(test)]
mod html_mermaid_update_link;
#[cfg(test)]
mod html_mozilla_firefox_firefox_remove_li_around_button;
#[cfg(test)]
mod html_twbs_bootstrap_add_the_same_attribute_in_many_places;
#[cfg(test)]
mod java_genymobile_scrcpy_change_some_android_version_constant;
#[cfg(test)]
mod java_genymobile_scrcpy_refactor_for_loop_in_a_function;
#[cfg(test)]
mod java_genymobile_scrcpy_switch_from_three_exceptions_to_one;
#[cfg(test)]
mod java_nextcloud_android_add_if_branch_with_reused_return;
#[cfg(test)]
mod java_nextcloud_android_add_two_function_calls;
#[cfg(test)]
mod java_protobuf_add_two_annotations;
#[cfg(test)]
mod java_protocolbuffers_protobuf_add_a_method;
#[cfg(test)]
mod java_protocolbuffers_protobuf_add_import_and_update_field_access;
#[cfg(test)]
mod java_scrcpy_public_to_protected;
#[cfg(test)]
mod java_scrcpy_remove_or_expression;
#[cfg(test)]
mod javascript_microsoft_typescript_another_test_case_marked_with_strict;
#[cfg(test)]
mod javascript_microsoft_typescript_broken_js_remove_string_fragment;
#[cfg(test)]
mod javascript_microsoft_typescript_test_data_pretending_to_be_code_maybe_broken_parsing;
#[cfg(test)]
mod javascript_mozilla_firefox_add_comment;
#[cfg(test)]
mod javascript_twbs_bootstrap_comment_version_update;
#[cfg(test)]
mod javascript_typescript_add_strict_3;
#[cfg(test)]
mod javascript_typescript_add_use_strict;
#[cfg(test)]
mod javascript_typescript_interesting_small_edit_refactor;
#[cfg(test)]
mod javascript_typescript_use_strict_2;
#[cfg(test)]
mod javascript_typescript_very_interesting_brokn_code;
#[cfg(test)]
mod json_apache_string_change_version;
#[cfg(test)]
mod json_gorhill_ublock_add_5_pairs;
#[cfg(test)]
mod json_langflow_update_single_string;
#[cfg(test)]
mod json_mastodon_add_translation;
#[cfg(test)]
mod json_nextcloud_server_deleted_pair;
#[cfg(test)]
mod json_nextcloud_server_remove_many_and_move_one;
#[cfg(test)]
mod json_radarr_radarr_rename_string_key;
#[cfg(test)]
mod json_shadcn_ui_ui_react_code_in_string_constant;
#[cfg(test)]
mod json_shadcn_ui_ui_string_value_update_string_is_code;
#[cfg(test)]
mod kotlin_nextcloud_a_few_small_removals;
#[cfg(test)]
mod kotlin_nextcloud_android_add_a_feature;
#[cfg(test)]
mod kotlin_nextcloud_android_dot_to_question_mark_dot;
#[cfg(test)]
mod kotlin_nextcloud_android_extract_argument_into_variable;
#[cfg(test)]
mod kotlin_nextcloud_android_move_from_one_mocking_library_to_other;
#[cfg(test)]
mod kotlin_nextcloud_change_function_fingerprint;
#[cfg(test)]
mod kotlin_nextcloud_remove_function;
#[cfg(test)]
mod kotlin_nextcloud_whitespace_only_change;
#[cfg(test)]
mod kotlin_remove_function;
#[cfg(test)]
mod kotlin_small_api_change;
#[cfg(test)]
mod lua_awesome_only_comment_change;
#[cfg(test)]
mod lua_awesomewm_awesome_align_to_halign;
#[cfg(test)]
mod lua_awesomewm_awesome_change_doccomments;
#[cfg(test)]
mod lua_awesomewm_awesome_comment_changes_and_additions;
#[cfg(test)]
mod lua_neovim_neovim_add_if_around_one_line;
#[cfg(test)]
mod lua_neovim_neovim_add_new_logic;
#[cfg(test)]
mod lua_neovim_neovim_constant_changes;
#[cfg(test)]
mod lua_neovim_neovim_if_flips_two_branches;
#[cfg(test)]
mod lua_neovim_one_added_line;
#[cfg(test)]
mod php_nextcloud_change_doccomment;
#[cfg(test)]
mod php_nextcloud_server_whitespace_and_added_declaration;
#[cfg(test)]
mod php_wordpress_wordpress_add_null_to_return;
#[cfg(test)]
mod php_wordpress_wordpress_add_rtc_check;
#[cfg(test)]
mod php_wordpress_wordpress_add_some_checks;
#[cfg(test)]
mod php_wordpress_wordpress_update_doccomment;
#[cfg(test)]
mod php_wordpress_wordpress_version_update;
#[cfg(test)]
mod php_wordpress_wordpress_version_update_2;
#[cfg(test)]
mod php_wordpress_wordpress_version_update_3;
#[cfg(test)]
mod php_wordpress_wordpress_whitespace_only_change;
#[cfg(test)]
mod python_ansible_ansible_field_rename;
#[cfg(test)]
mod python_langflow_ai_langflow_actual_change_of_logic;
#[cfg(test)]
mod python_openhands_openhands_change_string_constant;
#[cfg(test)]
mod python_paddlepaddle_paddleocr_formatting_only_change;
#[cfg(test)]
mod python_pandas_dev_pandas_doccoment_changes_only;
#[cfg(test)]
mod python_pytorch_pytorch_add_param_to_many_places_and_update_one;
#[cfg(test)]
mod python_thefuck_multiline_string_change;
#[cfg(test)]
mod python_ytdl_add_import_and_function_call;
#[cfg(test)]
mod ruby_homebrew_add_or_expression;
#[cfg(test)]
mod ruby_homebrew_brew_actual_logic_change;
#[cfg(test)]
mod ruby_homebrew_brew_change_heredoc_to_string;
#[cfg(test)]
mod ruby_homebrew_brew_enclose_block_in_rescue;
#[cfg(test)]
mod ruby_homebrew_brew_function_callsite_argument_change;
#[cfg(test)]
mod ruby_homebrew_brew_real_small_change;
#[cfg(test)]
mod ruby_junegunn_fzf_add_test_case;
#[cfg(test)]
mod ruby_junegunn_fzf_add_test_case_2;
#[cfg(test)]
mod ruby_mastodon_mastodon_use_context_and_new_test_case;
#[cfg(test)]
mod rust_rust_lang_rust_add_key_to_function_arguments_and_call_sites;
#[cfg(test)]
mod rust_rustdesk_add_item;
#[cfg(test)]
mod rust_rustdesk_add_one_slice_element;
#[cfg(test)]
mod rust_rustdesk_rustdesk_add_two_values_to_slice;
#[cfg(test)]
mod rust_rustdesk_rustdesk_string_constant_change;
#[cfg(test)]
mod rust_vercel_nextjs_move_from_one_struct_to_another_and_add_some_code;
#[cfg(test)]
mod rust_zed_industries_zed_add_argument;
#[cfg(test)]
mod shellscript_ansible_ansible_add_variable_and_string_expansion;
#[cfg(test)]
mod shellscript_ansible_ansible_simple_deletion;
#[cfg(test)]
mod shellscript_genymobile_scrcpy_add_two_flags;
#[cfg(test)]
mod shellscript_langchain_ai_langchain_some_interesting_raw_string_to_string_content;
#[cfg(test)]
mod shellscript_nextcloud_server_change_invocation_string;
#[cfg(test)]
mod shellscript_nvm_sh_nvm_upgrade_version_string;
#[cfg(test)]
mod shellscript_pi_hole_pi_hole_sql_code_in_string_constant;
#[cfg(test)]
mod shellscript_pytorch_pytorch_change_invocation_string;
#[cfg(test)]
mod shellscript_scikit_learn_scikit_learn_string_to_regex;
#[cfg(test)]
mod shellscript_torvalds_linux_double_equals_to_equals;
#[cfg(test)]
mod swift_nextcloud_ios_actual_control_flow_change;
#[cfg(test)]
mod swift_nextcloud_ios_actual_logic_added;
#[cfg(test)]
mod swift_nextcloud_ios_add_4_functions;
#[cfg(test)]
mod swift_nextcloud_ios_call_different_function;
#[cfg(test)]
mod swift_swiftlang_swift_actual_logic_change;
#[cfg(test)]
mod swift_swiftlang_swift_comment_change;
#[cfg(test)]
mod swift_swiftlang_swift_comment_change_2;
#[cfg(test)]
mod swift_swiftlang_swift_enable_checks_remove_todo_comment;
#[cfg(test)]
mod tsx_apache_superset_add_test_case;
#[cfg(test)]
mod tsx_apache_superset_error_handling_change;
#[cfg(test)]
mod tsx_excalidraw_excalidraw_import_path_change;
#[cfg(test)]
mod tsx_excalidraw_excalidraw_move_from_one_struct_to_other;
#[cfg(test)]
mod tsx_langflow_ai_langflow_move_function_around_update_string_constant;
#[cfg(test)]
mod tsx_material_remove_import;
#[cfg(test)]
mod tsx_mui_material_ui_move_colour_to_a_new_attribute;
#[cfg(test)]
mod tsx_shadcn_ui_ui_add_attribute;
#[cfg(test)]
mod tsx_shadcn_ui_ui_real_small_change;
#[cfg(test)]
mod typescript_excalidraw_excalidraw_add_function;
#[cfg(test)]
mod typescript_excalidraw_excalidraw_add_values_to_lists;
#[cfg(test)]
mod typescript_microsoft_playwright_add_two_test_cases;
#[cfg(test)]
mod typescript_microsoft_typescript_add_dot_js_to_import_paths;
#[cfg(test)]
mod typescript_microsoft_typescript_add_target_comment;
#[cfg(test)]
mod typescript_microsoft_typescript_comment_change;
#[cfg(test)]
mod typescript_n8n_io_n8n_remove_and_add_imports;
#[cfg(test)]
mod typescript_typescript_add_target_comment;
#[cfg(test)]
mod typescript_typescript_add_target_comment_2;
#[cfg(test)]
mod typescript_typescript_add_target_comment_3;
#[cfg(test)]
mod vimscript_junegunn_fzf_condition_canges;
#[cfg(test)]
mod vimscript_neovim_neovim_add_a_few_lines;
#[cfg(test)]
mod vimscript_neovim_neovim_add_a_few_lines_one_after_the_other;
#[cfg(test)]
mod vimscript_neovim_neovim_add_line_comment;
#[cfg(test)]
mod vimscript_neovim_neovim_add_test_case_plus_edit_existing_one;
#[cfg(test)]
mod vimscript_neovim_neovim_i_have_no_idea_what_this_diff_does;
#[cfg(test)]
mod vimscript_neovim_neovim_improved_asserts;
#[cfg(test)]
mod xml_microsoft_terminal_multiline_string_constant_change;
#[cfg(test)]
mod xml_mozilla_firefox_firefox_add_a_few_attributes;
#[cfg(test)]
mod xml_mozilla_firefox_firefox_add_a_few_translations_and_a_few_attributes;
#[cfg(test)]
mod xml_nextcloud_android_add_few_translations;
#[cfg(test)]
mod xml_nextcloud_android_delete_element;
#[cfg(test)]
mod xml_nextcloud_android_delete_element_2;
#[cfg(test)]
mod xml_odoo_odoo_add_attribute;
#[cfg(test)]
mod xml_odoo_odoo_add_button_roles;
#[cfg(test)]
mod xml_odoo_odoo_add_two_attributes;
#[cfg(test)]
mod xml_odoo_odoo_change_value;
#[cfg(test)]
mod yaml_ansible_ansible_add_two_sequence_items;
#[cfg(test)]
mod yaml_ansible_ansible_double_quote_scalar_change_possible_treesitter_weakness;
#[cfg(test)]
mod yaml_axios_axios_update_string_value;
#[cfg(test)]
mod yaml_junegunn_fzf_version_upgrade;
#[cfg(test)]
mod yaml_mastodon_mastodon_add_block_pair_translation;
#[cfg(test)]
mod yaml_mastodon_remove_one_pair;
#[cfg(test)]
mod yaml_mozilla_pdf_single_value_update;
#[cfg(test)]
mod yaml_n8n_io_n8n_add_performance_check_to_ci_config;
#[cfg(test)]
mod yaml_twbs_bootstrap_version_pin_with_comment;
