/*  This file is part of the CodeDiff code diffing tool.
 *
 *  Copyright (C) 2026 Marko Ivankovic
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
#[cfg(test)]
mod c_cpython_autogenerated_code;
#[cfg(test)]
mod c_ffmpeg_added_typedef_to_enum;
#[cfg(test)]
mod c_freeciv_add_parameter_to_function;
#[cfg(test)]
mod c_htop_remove_function_declaration;
#[cfg(test)]
mod c_linux_small_bugfix;
#[cfg(test)]
mod c_linux_small_change;
#[cfg(test)]
mod c_linux_small_change_struct_to_char;
#[cfg(test)]
mod c_microsoft_terminal_add_function;
#[cfg(test)]
mod c_nginx_add_typedef;
#[cfg(test)]
mod c_postgres_real_logic_change;
#[cfg(test)]
mod cpp_add_const_correctness;
#[cfg(test)]
mod cpp_add_memory_management;
#[cfg(test)]
mod cpp_add_templates;
#[cfg(test)]
mod cpp_fix_segfault;
#[cfg(test)]
mod cpp_godot_small_bugfix;
#[cfg(test)]
mod cpp_ladybird_refactor_variables_if_changes;
#[cfg(test)]
mod cpp_laydbird_change_function_signature;
#[cfg(test)]
mod cpp_libreoffice_add_const;
#[cfg(test)]
mod cpp_libreoffice_remove_return_value;
#[cfg(test)]
mod cpp_nextcloud_add_test_case;
#[cfg(test)]
mod cpp_ollama_add_function_argument;
#[cfg(test)]
mod cpp_opencv_add_test_case;
#[cfg(test)]
mod cpp_optimize_algorithm;
#[cfg(test)]
mod cpp_tensorflow_switch_to_primitive_types;
#[cfg(test)]
mod cpp_whitespace_only_change;
#[cfg(test)]
mod csharp_jellyfin_sql_query_fix;
#[cfg(test)]
mod csharp_sonarr_change_type;
#[cfg(test)]
mod css_add_property;
#[cfg(test)]
mod css_playwright_add_class_selector;
#[cfg(test)]
mod go_lazygit_add_to_if_condition;
#[cfg(test)]
mod go_prometheus_single_comment_change;
#[cfg(test)]
mod go_user_slices_library;
#[cfg(test)]
mod java_add_exception_handling;
#[cfg(test)]
mod java_add_interface;
#[cfg(test)]
mod java_add_logging;
#[cfg(test)]
mod java_fix_array_index;
#[cfg(test)]
mod java_refactor_constants;
#[cfg(test)]
mod javascript_add_array_method;
#[cfg(test)]
mod javascript_add_destructuring;
#[cfg(test)]
mod javascript_add_event_listener;
#[cfg(test)]
mod javascript_fix_promises;
#[cfg(test)]
mod javascript_refactor_arrow_func;
#[cfg(test)]
mod json_apache_string_change_version;
#[cfg(test)]
mod kotlin_add_data_class;
#[cfg(test)]
mod kotlin_add_null_check;
#[cfg(test)]
mod kotlin_add_validation;
#[cfg(test)]
mod kotlin_fix_loop_bug;
#[cfg(test)]
mod kotlin_nextcloud_a_few_small_removals;
#[cfg(test)]
mod kotlin_nextcloud_change_function_fingerprint;
#[cfg(test)]
mod kotlin_nextcloud_remove_function;
#[cfg(test)]
mod kotlin_refactor_function;
#[cfg(test)]
mod kotlin_remove_function;
#[cfg(test)]
mod kotlin_small_api_change;
#[cfg(test)]
mod python_add_remove_block;
#[cfg(test)]
mod python_added_if_block;
#[cfg(test)]
mod python_added_if_block_small;
#[cfg(test)]
mod python_api_change;
#[cfg(test)]
mod python_bugfix_loop;
#[cfg(test)]
mod python_refactoring;
#[cfg(test)]
mod rust_add_if;
#[cfg(test)]
mod rust_add_to_existing_use;
#[cfg(test)]
mod rust_add_value_to_enum;
#[cfg(test)]
mod rust_algorithm_change;
#[cfg(test)]
mod rust_cost_optimization;
#[cfg(test)]
mod rust_data_structure;
#[cfg(test)]
mod rust_error_handling;
#[cfg(test)]
mod rust_firefox_webrenderer_borders;
#[cfg(test)]
mod rust_hash_optimization;
#[cfg(test)]
mod rust_hello_world_added_message;
#[cfg(test)]
mod rust_hello_world_removed_message;
#[cfg(test)]
mod rust_leetcode_1_bugfix;
#[cfg(test)]
mod rust_next_font_imports_generator;
#[cfg(test)]
mod rust_no_change;
#[cfg(test)]
mod rust_sniffnet_protocol;
#[cfg(test)]
mod rust_tauri_api_build_1;
#[cfg(test)]
mod rust_tauri_api_build_2;
#[cfg(test)]
mod rust_tauri_cli_ios_dev;
#[cfg(test)]
mod rust_turbopack_module_rule;
#[cfg(test)]
mod rust_turbopack_persistence_tools_main;
#[cfg(test)]
mod rust_zed_git_panel_settings;
#[cfg(test)]
mod rust_zed_workspace_tasks;
#[cfg(test)]
mod typescript_add_error_handling;
#[cfg(test)]
mod typescript_add_generics;
#[cfg(test)]
mod typescript_add_type_annotations;
#[cfg(test)]
mod typescript_async_await;
#[cfg(test)]
mod typescript_refactor_interface;
