/*  This file is part of the CodeDiff code diffing tool.
 *
 *  Copyright (C) 2026 Marko Ivankovic
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
//! The entry points: `resolve_forest`, the oversized-pair fallback, and the context they thread
//! through everything else.
//!
//! Split out of `common.rs`, which was 4,426 lines.

#[allow(unused_imports)]
use super::*;

/// Per-`resolve_forest`-call context letting `ren()` refuse pairings that would contradict a
/// mapping some earlier pass already fixed. `PostorderIndexer` prunes already-matched descendants
/// out of the forest entirely, so without this, nothing stops the DP from matching a "hollowed
/// out" ancestor - one whose real child was pruned away into some unrelated part of the other
/// tree - to any other same-kind node, including ones that break the ancestor-order-preservation
/// every tree-edit-distance mapping is supposed to guarantee. Concretely: if `before_id`'s pruned
/// descendant landed at `t`, then `before_id` may only be matched to an ancestor-or-self of `t`;
/// symmetrically for the after side. (See the `rust-add-if` case this was written for: the
/// `if`/`else` wrapper statement was getting matched deep inside the sibling `if` branch its own
/// child had already been pruned into, for free, since both were internal nodes of the same kind.)
///
/// A second, related check covers pruning's other blind spot: an *unrelated sibling* of a pruned
/// node. That has no ancestor-descendant relationship to the pruned node at all, so the check
/// above can never catch it, yet the DP is just as free to match it across the pruned node's
/// former position as it is a hollowed-out ancestor. Concretely (the `python-refactoring` case
/// this was added for): once `average = total / count` is pre-matched and excised, nothing stops
/// `total = 0`'s `total` (positioned *before* `average` in the source) from being matched to some
/// unrelated `total` occurrence positioned *after* `average`'s counterpart, silently reordering
/// past a fixed point. Guarded the same way: `before_anchor_preorders`/`after_anchor_preorders`
/// hold the sorted `preorder_index` of every *trusted* pruned chunk root reachable from this
/// forest's roots (via `collect_pruned_chunk_pairs`, filtered down by
/// `longest_increasing_by_second` - see its doc comment for why not every pruned pair is safe to
/// trust), and a candidate pairing is only allowed if both nodes have the same *rank* - the same
/// count of trusted anchors preceding them - on their respective side. Comparing raw
/// `preorder_index` this way is safe for ancestor-descendant pairs too (an ancestor's
/// `preorder_index` always precedes all of its own descendants', so it can never be mis-ranked as
/// "after" a pruned node nested inside it) - no separate ancestor exclusion needed.
///
/// This second check is deliberately scoped to `source`s known to pre-match content the *same*
/// way `python-refactoring` needed guarding (currently `prematch_identical_statement_siblings`'s
/// two callers, `"qualified_name"`/`"large_flat_subtree_container"` - see `PREMATCH_SIBLING_ORDER_
/// SOURCES`), not enabled for every `resolve_forest` call the way the ancestor check above is.
/// Measured directly why: turning it on unconditionally regressed `c-cpython-autogenerated-code`
/// (33 -> 58 mismatches, later 35 with the `longest_increasing_by_second` filter above, still not
/// clean) via its `"greedy_anchor_block"`/`"final_pass"` calls, which anchor near-identical
/// *repeated* `case` bodies by content similarity, not by strict positional order - the opposite
/// of what this check assumes about its anchors. Rather than chase that heuristic's non-order-
/// preserving behavior through the LIS filter too, this stays opt-in per `source` until a second
/// caller actually needs it.
///
/// Built once per `resolve_forest` call and threaded down into `forest_dist` everywhere it's
/// invoked (both the keyroot sweep and the backtrace). Parent maps are only built when the
/// corresponding pruned-targets map is non-empty, so the common case (nothing pruned in this
/// particular forest) costs nothing beyond a few empty-collection checks.
pub(crate) struct ContainmentCtx<'a> {
    before_pruned_targets: rustc_hash::FxHashMap<usize, Vec<usize>>,
    after_pruned_targets: rustc_hash::FxHashMap<usize, Vec<usize>>,
    before_parents: &'a rustc_hash::FxHashMap<usize, usize>,
    after_parents: &'a rustc_hash::FxHashMap<usize, usize>,
    before_anchor_preorders: Vec<usize>,
    after_anchor_preorders: Vec<usize>,
    before_meta: &'a ASTMetadata,
    after_meta: &'a ASTMetadata,
}

/// `source` tags whose `resolve_forest` call should get `ContainmentCtx`'s sibling-order check -
/// see that struct's doc comment for why this isn't every `source`.
pub(crate) const PREMATCH_SIBLING_ORDER_SOURCES: &[&str] = &[
    "qualified_name",
    "large_flat_subtree_container",
    "unique_named_local",
];

impl<'a> ContainmentCtx<'a> {
    pub(crate) fn build(
        before_root_ids: &[usize],
        after_root_ids: &[usize],
        before_meta: &'a ASTMetadata,
        after_meta: &'a ASTMetadata,
        diff: &ASTDiff,
        source: &str,
    ) -> Self {
        let before_pruned_targets =
            compute_pruned_targets(before_root_ids, before_meta, &diff.before_node_map);
        let after_pruned_targets =
            compute_pruned_targets(after_root_ids, after_meta, &diff.after_node_map);
        let (before_anchor_preorders, after_anchor_preorders) =
            if PREMATCH_SIBLING_ORDER_SOURCES.contains(&source) {
                let mut anchor_preorders: Vec<(usize, usize)> = collect_pruned_chunk_pairs(
                    before_root_ids,
                    after_root_ids,
                    before_meta,
                    after_meta,
                    diff,
                )
                .into_iter()
                .filter_map(|(b, a)| {
                    let bp = before_meta.node_info.get(&b)?.preorder_index;
                    let ap = after_meta.node_info.get(&a)?.preorder_index;
                    Some((bp, ap))
                })
                .collect();
                anchor_preorders.sort_unstable();
                // Only the longest mutually order-consistent run is trusted as sibling-order
                // fixed points - see `longest_increasing_by_second`'s doc comment for why. Both
                // projections come out already sorted: `.0` because it's a subsequence of
                // `anchor_preorders` (sorted by `.0`), `.1` because that's exactly what the LIS
                // enforces.
                let trusted = longest_increasing_by_second(&anchor_preorders);
                (
                    trusted.iter().map(|&(b, _)| b).collect(),
                    trusted.iter().map(|&(_, a)| a).collect(),
                )
            } else {
                (Vec::new(), Vec::new())
            };
        // Parent maps are precomputed once per file in `ASTMetadata` (see `node_to_parent`), so
        // borrowing them here - even when this particular forest has nothing pruned and won't
        // end up using them - costs nothing beyond the borrow itself.
        ContainmentCtx {
            before_pruned_targets,
            after_pruned_targets,
            before_parents: &before_meta.node_to_parent,
            after_parents: &after_meta.node_to_parent,
            before_anchor_preorders,
            after_anchor_preorders,
            before_meta,
            after_meta,
        }
    }

    /// Adjusts a `ren()`-computed `base` cost: if matching `before_id` to `after_id` would
    /// contradict where an already-pruned descendant of either landed, or would cross an
    /// unrelated pruned sibling in a way that reorders it, escalate to `FORBIDDEN_RENAME_COST` so
    /// the DP looks elsewhere. `base` is returned unchanged whenever there's nothing pruned to
    /// check against (the common case).
    pub(crate) fn adjust(&self, before_id: usize, after_id: usize, base: u64) -> u64 {
        if base >= FORBIDDEN_RENAME_COST {
            return base;
        }
        if let Some(targets) = self.before_pruned_targets.get(&before_id) {
            if targets
                .iter()
                .any(|&t| !is_ancestor_or_self(after_id, t, self.after_parents))
            {
                return FORBIDDEN_RENAME_COST;
            }
        }
        if let Some(targets) = self.after_pruned_targets.get(&after_id) {
            if targets
                .iter()
                .any(|&t| !is_ancestor_or_self(before_id, t, self.before_parents))
            {
                return FORBIDDEN_RENAME_COST;
            }
        }
        if !self.before_anchor_preorders.is_empty() || !self.after_anchor_preorders.is_empty() {
            let before_pre = self
                .before_meta
                .node_info
                .get(&before_id)
                .map(|info| info.preorder_index);
            let after_pre = self
                .after_meta
                .node_info
                .get(&after_id)
                .map(|info| info.preorder_index);
            if let (Some(bp), Some(ap)) = (before_pre, after_pre) {
                let rank_before = self.before_anchor_preorders.partition_point(|&p| p < bp);
                let rank_after = self.after_anchor_preorders.partition_point(|&p| p < ap);
                if rank_before != rank_after {
                    return FORBIDDEN_RENAME_COST;
                }
            }
        }
        base
    }
}

/// Resolve the mapping for a forest of (possibly already partially mapped) sibling roots on
/// each side. This is the single entry point that builds the pruned postorder indexers, runs
/// the keyroot-based forest-distance computation, and translates the result into `diff`.
/// Largest `before.size * after.size` (pruned node counts) a *single* subtree pair may hand to the
/// full tree-edit-distance engine. Above it, [`resolve_oversized_pair`] decomposes the pair one
/// level instead.
///
/// Every multi-root forest reaching `resolve_forest` is already bounded by its caller
/// (`FLAT_UNMATCHED_RECURSE_MAX_TOTAL_SIZE`, the residual segment caps), but a single pair never
/// was: `fast_fallback`'s per-position recursion, `qualified_name`'s per-entity call and
/// `large_flat_subtree_container` each hand over whole functions or classes of 500-1100 nodes,
/// and profiling (callgrind + gdb on every fixture over 400ms, 2026-09-01) found that one such
/// call was the entire latency story every time - the O(n*m)-and-worse edit-distance kernel on
/// a (848, 679) pair, not anything file-wide.
///
/// Calibrated 2026-09-02 by sweeping the corpus per fixture (`--compare`): 250,000 and 400,000
/// both regress `lua-luakit-luakit-actual-test-change-merging-two-tests-into-one` (107 -> 380) -
/// its whole file is one (848, 679) = 575,632-cell pair whose top-level statements all changed
/// quote style, so exact-hash anchoring finds nothing and the decomposition falls to shape
/// anchors and atomic delete/insert where full APTED aligned everything; 250,000 also trades
/// `c-graph-algorithms-...` (70 -> 87) for `c-postgres-real-logic-change` (27 -> 14). 600,000
/// is the first value with no fixture worse and none better: every pair the corpus needs solved
/// exactly stays exact, and the pairs above it (rustdesk's (716, 878), openvr's (1068, 1088))
/// decompose to the same mapping they had. Lowering it is a latency-for-quality trade that the
/// per-fixture gate will show; raising it buys nothing today.
pub(crate) const APTED_MAX_CELLS: usize = 600_000;

/// What `resolve_forest` does with a single pair over [`APTED_MAX_CELLS`]: pair the two roots
/// (or delete/insert them if their kinds may not meet), then resolve their children as an
/// anchored sequence exactly the way a flat container's children are - exact-hash LCS first,
/// leftovers positionally when the counts agree, as a bounded APTED pool otherwise. Each
/// leftover pair re-enters `resolve_forest` on its own, so the gate applies again a level down.
///
/// The decomposition is the same one every flat container already gets, so the risk is not a
/// new kind of guess but a coarser one: a function body that gained a statement *and* edited a
/// neighbour lands in the unequal-count branch, where the flat path's pool caps decide between a
/// bounded pool and atomic delete/insert. Measured per fixture before landing (see the commit).
pub(crate) fn resolve_oversized_pair(
    before_root: usize,
    after_root: usize,
    before_meta: &ASTMetadata,
    after_meta: &ASTMetadata,
    cost_model: &UnitCostModel,
    source: &'static str,
    diff: &mut ASTDiff,
) {
    let before_children = before_meta
        .node_info
        .get(&before_root)
        .map(|info| info.children.clone())
        .unwrap_or_default();
    let after_children = after_meta
        .node_info
        .get(&after_root)
        .map(|info| info.children.clone())
        .unwrap_or_default();

    let roots_may_pair = match (
        before_meta.node_info.get(&before_root),
        after_meta.node_info.get(&after_root),
    ) {
        (Some(b), Some(a)) => kinds_update_allowed(&b.kind, &a.kind, &before_meta.language),
        _ => false,
    };
    if roots_may_pair {
        let (operation, cost) =
            classify_match(before_root, after_root, before_meta, after_meta, cost_model);
        diff.add_mapping(
            before_root,
            after_root,
            ASTMapping {
                cost,
                operation,
                reason: ASTMappingReason::APTED(source),
            },
        );
    } else {
        // Root only - the children get their own decisions below, same as `emit_before_subtree`'s
        // "something below is reused" branch.
        diff.add_mapping(
            before_root,
            0,
            ASTMapping {
                cost: COST_DELETE,
                operation: ASTMappingOperation::Delete,
                reason: ASTMappingReason::APTED(source),
            },
        );
        diff.add_mapping(
            0,
            after_root,
            ASTMapping {
                cost: COST_INSERT,
                operation: ASTMappingOperation::Insert,
                reason: ASTMappingReason::APTED(source),
            },
        );
    }

    resolve_child_sequence(
        before_children,
        after_children,
        before_meta,
        after_meta,
        LeftoverPool::Oversized,
        source,
        diff,
    );
}

/// Which tree-edit-distance algorithm `resolve_forest` should run to populate the delta table
/// that `compute_edit_mapping` then backtraces through. Both produce optimal distances; this is
/// purely a backend choice threaded through from `for_roots`/`for_nodes`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Algorithm {
    ZhangShasha,
    Apted,
}

// Each parameter is genuinely distinct context (both root-id lists, both metadata sets, the
// algorithm choice, the diff) - a params struct here would just relocate the same fields, not
// reduce them.
#[allow(clippy::too_many_arguments)]
pub(crate) fn resolve_forest(
    before_root_ids: Vec<usize>,
    after_root_ids: Vec<usize>,
    before_meta: &ASTMetadata,
    after_meta: &ASTMetadata,
    cost_model: &UnitCostModel,
    algorithm: Algorithm,
    source: &'static str,
    diff: &mut ASTDiff,
) {
    let before_root_ids = filter_mapped_nodes(&before_root_ids, &diff.before_node_map);
    let after_root_ids = filter_mapped_nodes(&after_root_ids, &diff.after_node_map);
    if before_root_ids.is_empty() && after_root_ids.is_empty() {
        return;
    }
    if before_root_ids.is_empty() {
        for id in after_root_ids {
            add_insert_mappings(id, after_meta, source, diff);
        }
        return;
    }
    if after_root_ids.is_empty() {
        for id in before_root_ids {
            add_delete_mappings(id, before_meta, source, diff);
        }
        return;
    }

    // Fast path: a single root pair whose subtrees are bit-for-bit identical (same structure
    // and same leaf values) never benefits from running the expensive tree-edit-distance
    // machinery - just walk both subtrees in lockstep and mark everything Identical. Unlike a
    // general hash-based pre-matching pass over arbitrary interior nodes (tried and reverted -
    // see git history - it could pick a same-kind-but-unrelated node as a "free rename" partner
    // for genuinely new content, since the cost model treats any two same-kind internal nodes
    // as freely renameable regardless of content), this is always safe: it only ever matches
    // the exact pair it was asked to resolve, never an arbitrary interior node.
    if before_root_ids.len() == 1 && after_root_ids.len() == 1 {
        let b = before_root_ids[0];
        let a = after_root_ids[0];
        let hashes_match = before_meta
            .node_to_full_hash
            .get(&b)
            .zip(after_meta.node_to_full_hash.get(&a))
            .is_some_and(|(bh, ah)| bh == ah);
        if hashes_match {
            emit_identical_subtree(b, a, before_meta, after_meta, source, diff);
            return;
        }
        // Fast path: flat trees (single root, all leaf children) → Myers O(ND) sequence diff.
        // Zhang-Shasha has no structural savings on depth-1 trees; Myers is O(N·d) where d is
        // the edit distance, typically much smaller than N for lightly-modified files.
        if let (Some(bc), Some(ac)) = (flat_children(b, before_meta), flat_children(a, after_meta))
        {
            resolve_flat_tree_pair(b, a, bc, ac, before_meta, after_meta, source, diff);
            return;
        }
        // A thin wrapper around a flat container - `struct_specifier` around its
        // `field_declaration_list`, `class_declaration` around its `class_body` - gets the same
        // one-level decomposition an oversized pair does, so the flat container underneath
        // reaches the Myers path above instead of the wrapper being solved as one ordered tree.
        // Same kind on both sides is required of the flat child only; the wrappers themselves
        // are the pair the caller already decided corresponds.
        // Ordered tree-edit-distance cannot express a reordering of the container's members at
        // all: `c-sched-ext-scx-many-many-moves-...` (2026-09-02) is a 100-field struct whose
        // fields moved, and general APTED on the `struct_specifier` pair mis-paired 96 of them
        // with same-shaped neighbours (245 mismatches), while the flat path one level down
        // anchors every moved field by exact hash and by name.
        if let (Some(bf), Some(af)) = (
            sole_flat_child(b, before_meta),
            sole_flat_child(a, after_meta),
        ) && before_meta.node_info.get(&bf).map(|i| &i.kind)
            == after_meta.node_info.get(&af).map(|i| &i.kind)
        {
            resolve_oversized_pair(b, a, before_meta, after_meta, cost_model, source, diff);
            return;
        }
    }

    let before_idx = PostorderIndexer::build(before_meta, &before_root_ids, &diff.before_node_map);
    let after_idx = PostorderIndexer::build(after_meta, &after_root_ids, &diff.after_node_map);

    if before_root_ids.len() == 1
        && after_root_ids.len() == 1
        && before_idx.size * after_idx.size > APTED_MAX_CELLS
    {
        resolve_oversized_pair(
            before_root_ids[0],
            after_root_ids[0],
            before_meta,
            after_meta,
            cost_model,
            source,
            diff,
        );
        return;
    }

    // Built once and threaded into every `ren()` evaluation below (both the delta sweep and the
    // backtrace), so a "hollowed out" ancestor left behind by pruning can't freely rename onto a
    // node that would contradict where its pruned descendant already landed. See `ContainmentCtx`.
    let containment = ContainmentCtx::build(
        &before_root_ids,
        &after_root_ids,
        before_meta,
        after_meta,
        diff,
        source,
    );

    // `compute_delta` (engine.rs) is now containment-aware: `EngineCtx.containment` is threaded
    // into every `vren` call site (`spf_a`'s `ren_cost` closure, `apted_tree_edit_dist` for both
    // `PostDir`s) via `vren_adjusted`, mirroring the `ctx.adjust(...)` call in
    // `forest_dist`'s own `ren` computation (Zhang-Shasha side). So, unlike before, the algorithm
    // choice below no longer needs to fall back to `Algorithm::ZhangShasha` just because this
    // forest has real pruned-descendant constraints - both engines respect them identically.
    // Verified via `test_apted_engine_matches_oracle_fuzz_with_containment` (fuzzes forests with
    // genuine containment constraints, comparing Apted-with-containment against
    // Zhang-Shasha-with-containment) plus a manual check that each of the three `vren_adjusted`
    // sites, when individually disabled, makes that fuzz test fail on a real cost divergence.
    let mut delta = match algorithm {
        Algorithm::ZhangShasha => compute_delta_zhang_shasha(
            &before_idx,
            &after_idx,
            before_meta,
            after_meta,
            cost_model,
            Some(&containment),
        ),
        Algorithm::Apted => compute_delta(
            &before_idx,
            &after_idx,
            before_meta,
            after_meta,
            cost_model,
            &before_root_ids,
            &after_root_ids,
            &diff.before_node_map,
            &diff.after_node_map,
            Some(&containment),
        ),
    };
    let decisions = compute_edit_mapping(
        &before_idx,
        &after_idx,
        before_meta,
        after_meta,
        cost_model,
        Some(&containment),
        &mut delta,
    );
    let mut before_decision: HashMap<usize, BeforeDecision> = HashMap::new();
    let mut after_decision: HashMap<usize, AfterDecision> = HashMap::new();
    for decision in &decisions {
        match *decision {
            RawDecision::Match(b, a) => {
                before_decision.insert(b, BeforeDecision::Match(a));
                after_decision.insert(a, AfterDecision::Match(b));
            }
            RawDecision::Delete(b) => {
                before_decision.insert(b, BeforeDecision::Delete);
            }
            RawDecision::Insert(a) => {
                after_decision.insert(a, AfterDecision::Insert);
            }
        }
    }

    improve_slot_alignment(
        before_meta,
        after_meta,
        diff,
        &before_root_ids,
        &before_meta.node_to_parent,
        &after_meta.node_to_parent,
        &mut before_decision,
        &mut after_decision,
    );

    let mut before_has_match_below = HashMap::new();
    for &id in &before_root_ids {
        compute_has_match_below(
            id,
            before_meta,
            |n| diff.before_node_map.get(&n).is_some_and(|&x| x != 0),
            |n| matches!(before_decision.get(&n), Some(BeforeDecision::Match(_))),
            &mut before_has_match_below,
        );
    }
    let mut after_has_match_below = HashMap::new();
    for &id in &after_root_ids {
        compute_has_match_below(
            id,
            after_meta,
            |n| diff.after_node_map.get(&n).is_some_and(|&x| x != 0),
            |n| matches!(after_decision.get(&n), Some(AfterDecision::Match(_))),
            &mut after_has_match_below,
        );
    }

    let ctx = ResolveCtx {
        before_meta,
        after_meta,
        before_decision,
        after_decision,
        before_has_match_below,
        after_has_match_below,
        source,
    };

    for &id in &before_root_ids {
        emit_before_subtree(id, &ctx, diff);
    }
    for &id in &after_root_ids {
        if matches!(ctx.after_decision.get(&id), Some(AfterDecision::Insert)) {
            emit_after_subtree(id, &ctx, diff);
        }
    }
}

/// Compute the optimal tree edit distance using a postorder, single-node-granularity
/// Zhang-Shasha/APTED-style forest distance, given before/after node id lists.
///
/// `source` is a short, call-site-specific label (e.g. `"final_pass"`, `"bottom_up_expansion"`)
/// recorded on every `ASTMappingReason::APTED` entry this resolution produces - see that variant's
/// doc comment. Every caller passes a distinct literal identifying which heuristic invoked APTED,
/// so two `APTED`-reasoned mappings can be told apart by provenance, not just by the fact that
/// APTED produced both.
pub fn for_nodes(
    before_metadata: &ASTMetadata,
    after_metadata: &ASTMetadata,
    before_node_ids: Vec<usize>,
    after_node_ids: Vec<usize>,
    algorithm: Algorithm,
    source: &'static str,
    diff: &mut ASTDiff,
) {
    let cost_model = UnitCostModel::new(before_metadata.language);
    resolve_forest(
        before_node_ids,
        after_node_ids,
        before_metadata,
        after_metadata,
        &cost_model,
        algorithm,
        source,
        diff,
    );
}

/// Compute the tree edit distance for root nodes, using whichever `algorithm` the caller picks.
/// See `for_nodes` for what `source` records.
pub fn for_roots(
    before: &Code,
    after: &Code,
    _node_cache: &NodeCache,
    algorithm: Algorithm,
    source: &'static str,
    diff: &mut ASTDiff,
) {
    // Fail safe rather than panic when either side has no AST (e.g. `Language::Unknown` and
    // several other languages tree-sitter has no grammar for - `Code::from_string`/`parse`
    // deliberately leave `ast: None` for those, a valid state, not a bug - see `code.rs`'s
    // doc comment on `Code::parse`). `Diff`'s own doc comment promises every function taking a
    // `Code` should "fail-safe... returning a safe zero result" - with no root node to anchor on,
    // there is nothing this phase can match, so it's a no-op rather than a crash.
    if before.ast.is_none() || after.ast.is_none() {
        return;
    }

    // Compute metadata once at the top level
    let before_metadata = crate::code::metadata::metadata_of(before);
    let after_metadata = crate::code::metadata::metadata_of(after);

    let before_root_id = before.ast.as_ref().unwrap().root_node().id();
    let after_root_id = after.ast.as_ref().unwrap().root_node().id();

    for_nodes(
        &before_metadata,
        &after_metadata,
        vec![before_root_id],
        vec![after_root_id],
        algorithm,
        source,
        diff,
    );
}
