/*  This file is part of the CodeDiff code diffing tool.
 *
 *  Copyright (C) 2026 Marko Ivankovic
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
use std::collections::HashMap;

use tree_sitter::Node;

use crate::code::{Code, Language};
use crate::code::metadata::metadata_of;
use crate::diff::apted::{self, Algorithm};
use crate::diff::{
    ASTDiff, NodeCache, grouped_greedy_matcher, nodes, solve_greedy_anchor_blocks, solve_large_flat_subtrees,
    solve_similar_flow_control,
};

/**
* Phase 4 of the seven-phase pipeline (`TODO.md`, 2026-07-17/18): "syntax-aware subtree matching".
* Named-group matching (below), positional anchoring (`solve_greedy_anchor_blocks`), and
* flow-control arm-overlap (`solve_similar_flow_control`) turned out, on inspection (`TODO.md`'s
* "generalization of phase 4" analysis, 2026-07-18), to be the same algorithm with three different
* (candidate predicate, compatibility key, cost function) tuples plugged in - all three now share
* one engine, `grouped_greedy_matcher::solve`: partition candidates into buckets by an exact key,
* score same-key pairs with a cheap cost function, greedily accept the cheapest first (optionally
* above a threshold), hand accepted pairs to real APTED. This module's own contribution to that
* shared shape is [`solve_named_reference_groups`] - **fully-resolved names** (scope-qualified,
* e.g. `"Bar::new"` rather than bare `"new"`) as the compatibility key, supporting real N:M
* (overloads, trait-impl duplicates) and no rejection threshold at all (the shared name already
* *is* the identity signal - see that function's doc comment for why).
*
* `solve_large_flat_subtrees` is the fourth pass this phase absorbs, but it doesn't fit the
* grouped-matching shape (no competing candidates, no scoring) - it's a deterministic lookup
* executed *inside* an already-identity-matched pair purely to pre-empt part of that pair's own
* APTED call. It runs first, same ordering the old pipeline used: `TODO.md`'s original plan bet
* that `resolve_forest`'s flat-tree fast path would catch a flat descendant with no dedicated call
* needed once a pair reaches `apted::for_nodes` - measured false on `c-cpython-autogenerated-code`
* (a huge autogenerated `switch` nested many levels under the function/impl that the name-based
* signal matches as one whole-subtree APTED call, so the fast path never gets a chance to fire on
* the flat descendant specifically). Pre-empting it explicitly here fixed a 141-mismatch regression
* on that fixture - see `TODO.md`.
*/
pub fn solve(
    before: &Code,
    after: &Code,
    node_cache: &NodeCache,
    diff: &mut ASTDiff,
    solve_similar_flow_control_enabled: bool,
) {
    solve_large_flat_subtrees::solve(before, after, diff);
    solve_named_reference_groups(before, after, diff);
    solve_greedy_anchor_blocks::solve(before, after, node_cache, diff);
    if solve_similar_flow_control_enabled {
        solve_similar_flow_control::solve(before, after, node_cache, diff);
    }
}

/**
* Matches `nodes::is_semantically_structural` candidates (functions, classes, structs, enums,
* impls, ...) by **fully-resolved name**: `(kind, name)` where `name` is scope-qualified by
* prepending every enclosing named node's own name, joined by `::` - e.g. a `new` method inside
* `impl Bar` resolves to `"Bar::new"`, distinguishing it from `Foo::new` without the dedicated
* impl/class method pre-pass `solve_semantically_structural_nodes` needed (Pass 0b/Pass 1 there):
* the scope qualification *is* the disambiguation, for every kind, uniformly.
*
* Grouped into `HashMap<(kind, fully_resolved_name), Vec<node_id>>` (a `Vec`, not a single id) to
* support real N:M: overloads, duplicate trait impls, or any other case where more than one
* candidate shares the same key on one or both sides.
*
* Unlike the positional/arm-overlap signals this phase also uses (via `solve_greedy_anchor_blocks`/
* `solve_similar_flow_control`), matching here is **not** gated by a cost-ratio rejection
* threshold: the shared fully-resolved name already *is* the identity signal (this declaration
* exists on both sides, however much its content changed - even a 100%-rewritten function body is
* still "the same function" if the name didn't change), so cost is only used to break ties *within*
* a multi-candidate group (deciding *which* overload pairs with which), never to reject a pair
* outright. `solve_greedy_anchor_blocks::cost_ratio` (the same `sequence_edit_cost`-based estimate)
* is reused for that tie-break, cheapest first, one-to-one within the group.
*
* Runs before the positional/arm-overlap signals in [`solve`] so a container that could be matched
* by *either* an outer named declaration or an inner anonymous block gets the stronger, name-based
* signal first - same "identity beats position, position beats coincidence" ordering the old
* pipeline's Pass 1-3 already encoded.
*/
fn solve_named_reference_groups(before: &Code, after: &Code, diff: &mut ASTDiff) {
    let before_metadata = metadata_of(before);
    let after_metadata = metadata_of(after);
    let language = before_metadata.language;

    let Some(before_root) = before.ast.as_ref().map(|ast| ast.root_node()) else { return };
    let Some(after_root) = after.ast.as_ref().map(|ast| ast.root_node()) else { return };

    let before_groups = collect_fully_resolved_groups(before_root, &language, before);
    let after_groups = collect_fully_resolved_groups(after_root, &language, after);

    // Flatten into (id, key) candidate lists for `grouped_greedy_matcher`, sorted by
    // `preorder_index` to satisfy its determinism contract - `collect_fully_resolved_groups`'
    // per-key `Vec`s are already in document order, but the flattened union across keys needs
    // its own global sort (`HashMap` key iteration order is not deterministic).
    let mut before_candidates: Vec<(usize, (String, String))> =
        before_groups.iter().flat_map(|(key, ids)| ids.iter().map(move |&id| (id, key.clone()))).collect();
    before_candidates
        .sort_by_key(|(id, _)| before_metadata.node_info.get(id).map(|i| i.preorder_index).unwrap_or(usize::MAX));
    let mut after_candidates: Vec<(usize, (String, String))> =
        after_groups.iter().flat_map(|(key, ids)| ids.iter().map(move |&id| (id, key.clone()))).collect();
    after_candidates
        .sort_by_key(|(id, _)| after_metadata.node_info.get(id).map(|i| i.preorder_index).unwrap_or(usize::MAX));

    grouped_greedy_matcher::solve(
        diff,
        &before_candidates,
        &after_candidates,
        |before_id, after_id| {
            solve_greedy_anchor_blocks::cost_ratio(before_id, after_id, &before_metadata, &after_metadata)
                .unwrap_or(0.0)
        },
        None,
        |before_id, after_id, diff| {
            apted::for_nodes(
                &before_metadata,
                &after_metadata,
                vec![before_id],
                vec![after_id],
                Algorithm::Apted,
                "syntax_named",
                diff,
            );
        },
    );
}

/// Recursive top-down walk building `HashMap<(kind, fully_resolved_name), Vec<node_id>>` - see
/// `solve_named_reference_groups`'s doc comment for what "fully resolved" means. `scope` is the
/// stack of enclosing named nodes' own (unqualified) names, outermost first; only nodes for which
/// `nodes::is_semantically_structural` returns a name push onto it, so intermediate structural
/// wrappers with no name of their own (Rust's `declaration_list`, Python's class `block`, ...)
/// don't break scope inheritance - a method two wrapper-levels under `impl Bar` still resolves to
/// `"Bar::method"`, not `"Bar::declaration_list::method"`.
fn collect_fully_resolved_groups(
    root: Node,
    language: &Language,
    code: &Code,
) -> HashMap<(String, String), Vec<usize>> {
    let mut out = HashMap::new();
    let mut scope: Vec<String> = Vec::new();
    collect_fully_resolved_groups_rec(root, language, code, &mut scope, &mut out);
    out
}

fn collect_fully_resolved_groups_rec(
    node: Node,
    language: &Language,
    code: &Code,
    scope: &mut Vec<String>,
    out: &mut HashMap<(String, String), Vec<usize>>,
) {
    let mut pushed_scope = false;
    if let Some((kind, name)) = nodes::is_semantically_structural(&node, language, code) {
        let full_name =
            if scope.is_empty() { name.clone() } else { format!("{}::{}", scope.join("::"), name) };
        out.entry((kind, full_name)).or_default().push(node.id());
        scope.push(name);
        pushed_scope = true;
    }

    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        collect_fully_resolved_groups_rec(child, language, code, scope, out);
    }

    if pushed_scope {
        scope.pop();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::code::Language;
    use crate::diff::ASTMappingOperation;

    #[test]
    fn methods_in_different_impls_are_matched_within_their_own_impl() {
        // Same regression guard as solve_semantically_structural_nodes' equivalent test: two
        // impls both define `new`. Fully-resolved names ("Foo::new" vs "Bar::new") disambiguate
        // them without any dedicated impl-scoped pre-pass.
        let before_src = "
struct Foo;
struct Bar;
impl Foo { fn new() -> Foo { Foo } }
impl Bar { fn new() -> Bar { Bar } }
";
        let after_src = "
struct Foo;
struct Bar;
impl Foo { fn new() -> Foo { Foo } }
impl Bar { fn new() -> Bar { Bar::default() } }
";
        let before = Code::from_string(before_src, &Language::Rust);
        let after = Code::from_string(after_src, &Language::Rust);
        let node_cache = NodeCache::build(&before, &after);
        let mut diff = ASTDiff::default();
        solve(&before, &after, &node_cache, &mut diff, true);

        let before_root = before.ast.as_ref().unwrap().root_node();
        let after_root = after.ast.as_ref().unwrap().root_node();

        let foo_new_mapping = crate::test::helper::mapping_for_path(
            &["impl_item:1", "declaration_list", "function_item"],
            &["impl_item:1", "declaration_list", "function_item"],
            before_root,
            after_root,
            &diff,
        )
        .unwrap();
        assert_eq!(foo_new_mapping.operation, ASTMappingOperation::Identical, "Foo::new should be identical");

        let bar_new_mapping = crate::test::helper::mapping_for_path(
            &["impl_item:2", "declaration_list", "function_item"],
            &["impl_item:2", "declaration_list", "function_item"],
            before_root,
            after_root,
            &diff,
        )
        .unwrap();
        assert_eq!(
            bar_new_mapping.operation,
            ASTMappingOperation::MatchButNotIdentical,
            "Bar::new should be changed"
        );
    }

    #[test]
    fn overloaded_same_name_functions_are_matched_nm() {
        // Two `impl_item`s for the same type (no trait) collide on plain `is_semantically_
        // structural` keying in today's pass - a real N:M case the fully-resolved-name grouping
        // must still handle via cost-based tie-break within the group, since both impls key to
        // the exact same fully-resolved name ("Foo") when there's no trait to disambiguate them.
        let before_src = "
struct Foo;
impl Foo { fn a() -> i32 { 1 } }
impl Foo { fn b() -> i32 { 2 } }
";
        let after_src = "
struct Foo;
impl Foo { fn a() -> i32 { 10 } }
impl Foo { fn b() -> i32 { 20 } }
";
        let before = Code::from_string(before_src, &Language::Rust);
        let after = Code::from_string(after_src, &Language::Rust);
        let node_cache = NodeCache::build(&before, &after);
        let mut diff = ASTDiff::default();
        solve(&before, &after, &node_cache, &mut diff, true);

        // Both `fn a` and `fn b` should end up mapped somewhere (not left as orphans) regardless
        // of which of the two same-keyed `impl Foo` blocks they were grouped under.
        let before_ast = before.ast.as_ref().unwrap();
        let mapped_fn_count = before_ast
            .root_node()
            .children(&mut before_ast.root_node().walk())
            .filter(|n| n.kind() == "impl_item")
            .flat_map(|impl_node| {
                let mut cursor = impl_node.walk();
                impl_node
                    .children(&mut cursor)
                    .collect::<Vec<_>>()
                    .into_iter()
                    .flat_map(|decl_list| {
                        let mut c2 = decl_list.walk();
                        decl_list.children(&mut c2).collect::<Vec<_>>()
                    })
                    .filter(|n| n.kind() == "function_item")
                    .collect::<Vec<_>>()
            })
            .filter(|n| diff.before_node_map.contains_key(&n.id()))
            .count();
        assert_eq!(mapped_fn_count, 2, "both overloaded-name functions should be mapped");
    }
}
