/*  This file is part of the CodeDiff code diffing tool.
 *
 *  Copyright (C) 2026 Marko Ivankovic
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
use std::collections::HashMap;

use crate::code::{ASTMetadata, Code};
use crate::diff::nodes::{anchor_pair_via_apted, kinds_update_allowed};
use crate::diff::{ASTDiff, ASTMappingReason, NodeCache};

/// BottomUpExpansion: once most of an unmatched node's descendants are already matched to the
/// descendants of some unmatched node on the other side, match the two nodes to each other too -
/// even though nothing matched their labels or full subtree hashes directly (e.g. a renamed
/// function whose body is otherwise unchanged, or a container whose name-based anchor never
/// fired). See `TODO.md`'s "bottom-up-extension" entry.
///
/// Two stages, run per candidate:
/// 1. Cheap candidate proposal: for each still-unmatched before-node, tally which after-side
///    parent each of its already-matched *direct children*'s counterparts belongs to, and take
///    the after-node with the most votes. This alone is too coarse to accept on (a node with a
///    handful of fixed-arity children, e.g. a function signature, can never tolerate even one
///    differing child under a 90% *direct-children* ratio - the one differing child, its own
///    name, blows the whole budget), but it narrows the O(before-nodes x after-nodes) search down
///    to one candidate per before-node in O(children) time.
/// 2. Dice-coefficient verification over the *entire* subtree (`DICE_THRESHOLD`): count how many
///    of the before-node's descendants (at any depth, not just direct children) already have a
///    real counterpart that falls inside the candidate's subtree, then require
///    `2 * common / (size_before + size_after) >= DICE_THRESHOLD`. This is what actually captures
///    "the body matches, only the name differs" - classic GumTree bottom-up matching.
///
/// Accepted pairs are handed to `apted::for_nodes` - the same "pre-match children, then diff the
/// container" idiom `solve_similar_flow_control` and `solve_syntax_aware_matching` use for
/// the same reason: it guarantees the result is complete (nothing under the pair is left unmapped
/// for a later pass to never revisit, since any already-mapped subtree is pruned from every later
/// forest) and gets a real edit-distance-based cost/operation instead of an invented one. Only the
/// `reason` on the resulting root mapping is overwritten afterward, to `BottomUpExpansion`, for
/// provenance/explainability.
///
/// Runs bottom-up in a single sweep: candidates are visited deepest-first, so by the time an
/// ancestor is considered, all of its descendants already had their chance to match in this same
/// call, letting one call propagate a match several levels up the tree.
///
/// Called from exactly one place in `Diff::from_code` - right before phase 6 (final APTED, via
/// `apted::for_roots`/`for_roots_fallback`) blanket-deletes/inserts everything still unmatched.
/// That's deliberate, not just "last chance to salvage a real orphan before phase 6 destroys it":
/// an earlier version of this pass ran after every top-down heuristic in the pipeline, and while
/// harmless late, running it *before* `solve_syntax_aware_matching`/
/// `solve_similar_flow_control` let a merely-plausible Dice-coefficient candidate occasionally win
/// a node that one of those more precise, name-/pattern-based passes would otherwise have claimed
/// correctly - once matched here, that decision is irrevocable (the matched subtree is pruned out
/// of every later forest), so the "wrong" claim couldn't be undone. Regressed 4
/// `optimal_solutions` fixtures (`c-cpython-autogenerated-code`, `c-linux-small-bugfix`,
/// `c-postgres-real-logic-change`, `rust-next-font-imports-generator`) before being narrowed to
/// this single, late call site, which reproduces the baseline `cargo test --lib` FAILED set
/// exactly (310 passed / 0 failed) and the baseline `benchmark_optimal_solutions` TOTAL exactly
/// (742 mismatches / 0 unsolved) while still firing ~29 times across the fixture corpus.
///
/// `DICE_THRESHOLD` was swept from 0.5 to 0.95 against `benchmark_optimal_solutions` (2026-07-11):
/// 0.8-0.95 all tie the 742/0 baseline exactly (same mismatch count on every single fixture, not
/// just the same TOTAL); 0.78 and below start regressing (0.78 -> 746, 0.75 -> 749, 0.5 -> 826).
/// The regressions are real, not tie-broken alternate-optimal-solutions: the extra mismatches are
/// on content-bearing nodes (`identifier`, `scoped_identifier`, `field_initializer`, a nested
/// `statement_block` matched to the wrong arrow function), not generic/punctuation tokens like `}`
/// or `)` that would suggest an equally-valid alternate mapping. No throughput difference was
/// measurable either (one release-build, single-run comparison: ~354s at 0.85 vs. ~352s with the
/// pass effectively disabled, i.e. within noise) - so there's no evidence for moving off 0.9, which
/// keeps the largest safety margin from the ~0.79 regression cliff for zero measured cost.
const DICE_THRESHOLD: f64 = 0.9;
/// Nodes with fewer children, or a smaller subtree, than these are never considered: matches on
/// tiny subtrees are noisy (a 2-node subtree clears any ratio the moment its one real child
/// matches) and are cheaply picked up by other passes anyway.
const MIN_CHILDREN: usize = 2;
const MIN_SUBTREE_SIZE: usize = 4;

pub fn solve(before: &Code, after: &Code, _node_cache: &NodeCache, diff: &mut ASTDiff) {
    let before_metadata = crate::code::metadata::metadata_of(before);
    let after_metadata = crate::code::metadata::metadata_of(after);
    let language = before_metadata.language;

    // Deepest nodes first (ties broken by `preorder_index`, not node id - see
    // `ASTNodeMetadata::start_byte`'s doc comment on why raw ids aren't parse-stable).
    let mut candidates: Vec<usize> = before_metadata.node_to_depth.keys().copied().collect();
    candidates.sort_by(|&a, &b| {
        let depth_a = before_metadata.node_to_depth.get(&a).copied().unwrap_or(0);
        let depth_b = before_metadata.node_to_depth.get(&b).copied().unwrap_or(0);
        depth_b.cmp(&depth_a).then_with(|| {
            let pre_a = before_metadata
                .node_info
                .get(&a)
                .map(|i| i.preorder_index)
                .unwrap_or(0);
            let pre_b = before_metadata
                .node_info
                .get(&b)
                .map(|i| i.preorder_index)
                .unwrap_or(0);
            pre_a.cmp(&pre_b)
        })
    });

    for before_id in candidates {
        if diff.before_node_map.contains_key(&before_id) {
            continue;
        }
        let Some(before_info) = before_metadata.node_info.get(&before_id) else {
            continue;
        };
        if before_info.children.len() < MIN_CHILDREN {
            continue;
        }
        let Some(&before_size) = before_metadata.node_to_subtree_size.get(&before_id) else {
            continue;
        };
        if before_size < MIN_SUBTREE_SIZE {
            continue;
        }

        // Stage 1: cheap candidate proposal via direct-children votes.
        let mut votes: HashMap<usize, usize> = HashMap::new();
        for &child_id in &before_info.children {
            let Some(&after_child_id) = diff.before_node_map.get(&child_id) else {
                continue;
            };
            if after_child_id == 0 {
                continue;
            }
            let Some(&after_parent_id) = after_metadata.node_to_parent.get(&after_child_id) else {
                continue;
            };
            *votes.entry(after_parent_id).or_insert(0) += 1;
        }
        if votes.is_empty() {
            continue;
        }

        // Highest vote count wins; ties broken by `preorder_index` so the choice is deterministic
        // no matter what order the `HashMap` above happens to iterate in.
        let mut best: Option<(usize, usize)> = None;
        for (after_id, count) in votes {
            let pre = after_metadata
                .node_info
                .get(&after_id)
                .map(|i| i.preorder_index)
                .unwrap_or(usize::MAX);
            let is_better = match best {
                None => true,
                Some((best_id, best_count)) => {
                    if count != best_count {
                        count > best_count
                    } else {
                        let best_pre = after_metadata
                            .node_info
                            .get(&best_id)
                            .map(|i| i.preorder_index)
                            .unwrap_or(usize::MAX);
                        pre < best_pre
                    }
                }
            };
            if is_better {
                best = Some((after_id, count));
            }
        }
        let Some((after_id, _)) = best else { continue };

        if diff.after_node_map.contains_key(&after_id) {
            continue;
        }
        let Some(after_info) = after_metadata.node_info.get(&after_id) else {
            continue;
        };
        if after_info.children.len() < MIN_CHILDREN {
            continue;
        }
        let Some(&after_size) = after_metadata.node_to_subtree_size.get(&after_id) else {
            continue;
        };
        if after_size < MIN_SUBTREE_SIZE {
            continue;
        }
        if before_info.kind != after_info.kind
            && !kinds_update_allowed(&before_info.kind, &after_info.kind, &language)
        {
            continue;
        }

        // Stage 2: verify with a full-subtree Dice coefficient.
        let common =
            common_descendant_count(before_id, after_id, &before_metadata, &after_metadata, diff);
        let dice = 2.0 * common as f64 / (before_size + after_size) as f64;
        if dice < DICE_THRESHOLD {
            continue;
        }

        anchor_pair_via_apted(
            before_id,
            after_id,
            &before_metadata,
            &after_metadata,
            "bottom_up_expansion",
            ASTMappingReason::BottomUpExpansion,
            diff,
        );
    }
}

/// Counts `before_id`'s descendants (any depth) whose already-recorded counterpart is a
/// descendant of `after_id` (or `after_id` itself). Relies on the pipeline-wide invariant that
/// once any node is added to `diff.before_node_map`, its entire subtree is too (every pass here
/// resolves the full forest under whatever roots it's given, never leaving a hole for a later pass
/// to find) - so a plain per-node lookup, no recursion into "is this subtree fully resolved yet",
/// is enough. Containment is checked via `after_id`'s preorder range, which is cheaper than
/// walking `node_to_parent` chains and works at any depth.
fn common_descendant_count(
    before_id: usize,
    after_id: usize,
    before_metadata: &ASTMetadata,
    after_metadata: &ASTMetadata,
    diff: &ASTDiff,
) -> usize {
    let Some(after_info) = after_metadata.node_info.get(&after_id) else {
        return 0;
    };
    let Some(&after_size) = after_metadata.node_to_subtree_size.get(&after_id) else {
        return 0;
    };
    let range_start = after_info.preorder_index;
    let range_end = range_start + after_size;

    let mut count = 0usize;
    let mut stack = vec![before_id];
    while let Some(id) = stack.pop() {
        if let Some(&partner) = diff.before_node_map.get(&id)
            && partner != 0
            && let Some(partner_info) = after_metadata.node_info.get(&partner)
            && partner_info.preorder_index >= range_start
            && partner_info.preorder_index < range_end
        {
            count += 1;
        }
        if let Some(info) = before_metadata.node_info.get(&id) {
            stack.extend(info.children.iter().copied());
        }
    }
    count
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::code::{Code, Language};
    use crate::diff::ASTMappingOperation;
    use crate::test::helper::find_first_of_kind as first_child_of_kind;

    #[test]
    fn renamed_function_with_mostly_matched_body_is_matched_via_bottom_up_expansion() {
        // Neither the function name nor the full/structural hash of the whole function matches
        // (the name changed), so name-based and hash-based passes never anchor the two
        // `function_item`s to each other. But once the rest of the function - parameters, return
        // type, and the entire body - are matched individually (simulated here the same way a
        // preceding pass would leave them), this pass should still recognize the containers as
        // "the same function, mostly unchanged" via the full-subtree Dice coefficient (a single
        // differing direct child, the identifier, would fail a naive direct-children ratio, but
        // is a tiny fraction of the whole subtree).
        let before_src = "fn compute(x: i32) -> i32 {\n    let a = 1;\n    let b = 2;\n    let c = 3;\n    a + b + c\n}\n";
        let after_src = "fn calculate(x: i32) -> i32 {\n    let a = 1;\n    let b = 2;\n    let c = 3;\n    a + b + c\n}\n";
        let before = Code::from_string(before_src, &Language::Rust);
        let after = Code::from_string(after_src, &Language::Rust);
        let node_cache = NodeCache::build(&before, &after);
        let mut diff = ASTDiff::default();

        // Simulate an earlier pass having matched everything except the `identifier` (function
        // name) and the enclosing `function_item` itself: map every other direct child
        // (`fn`, parameters, `->`, return type, block) positionally, recursing into each.
        let before_root = before.ast.as_ref().unwrap().root_node();
        let after_root = after.ast.as_ref().unwrap().root_node();
        let before_fn = first_child_of_kind(before_root, "function_item").unwrap();
        let after_fn = first_child_of_kind(after_root, "function_item").unwrap();
        let mut before_cursor = before_fn.walk();
        let mut after_cursor = after_fn.walk();
        let before_children: Vec<_> = before_fn.children(&mut before_cursor).collect();
        let after_children: Vec<_> = after_fn.children(&mut after_cursor).collect();
        for (b, a) in before_children.into_iter().zip(after_children) {
            if b.kind() == "identifier" {
                continue;
            }
            map_positionally(b, a, &mut diff);
        }

        solve(&before, &after, &node_cache, &mut diff);

        let mapping = diff
            .mapping
            .get(&(before_fn.id(), after_fn.id()))
            .expect("renamed function_item pair should be matched by bottom-up expansion");
        assert_eq!(mapping.reason, ASTMappingReason::BottomUpExpansion);
        assert_eq!(mapping.operation, ASTMappingOperation::MatchButNotIdentical);

        // The function name itself, which was deliberately left unmatched, should have been
        // resolved (as an Update) by the `apted::for_nodes` call this pass delegates to.
        let before_name = first_child_of_kind(before_fn, "identifier").unwrap();
        let after_name = first_child_of_kind(after_fn, "identifier").unwrap();
        assert_eq!(
            diff.before_node_map.get(&before_name.id()),
            Some(&after_name.id())
        );
    }

    #[test]
    fn dissimilar_containers_are_not_matched() {
        // Only 1 of 4 statements matches - well under the 90% Dice threshold - so the two blocks
        // (and therefore their enclosing functions) must not be paired up.
        let before_src =
            "fn a() {\n    let x = 1;\n    let y = 2;\n    let z = 3;\n    let w = 4;\n}\n";
        let after_src =
            "fn b() {\n    let p = 9;\n    let q = 8;\n    let r = 7;\n    let w = 4;\n}\n";
        let before = Code::from_string(before_src, &Language::Rust);
        let after = Code::from_string(after_src, &Language::Rust);
        let node_cache = NodeCache::build(&before, &after);
        let mut diff = ASTDiff::default();

        let before_root = before.ast.as_ref().unwrap().root_node();
        let after_root = after.ast.as_ref().unwrap().root_node();
        let before_fn = first_child_of_kind(before_root, "function_item").unwrap();
        let after_fn = first_child_of_kind(after_root, "function_item").unwrap();
        let before_block = first_child_of_kind(before_fn, "block").unwrap();
        let after_block = first_child_of_kind(after_fn, "block").unwrap();

        // Only map the one shared statement (`let w = 4;`), positionally last.
        let mut before_cursor = before_block.walk();
        let mut after_cursor = after_block.walk();
        let before_last = before_block
            .children(&mut before_cursor)
            .filter(|n| n.kind() == "let_declaration")
            .last()
            .unwrap();
        let after_last = after_block
            .children(&mut after_cursor)
            .filter(|n| n.kind() == "let_declaration")
            .last()
            .unwrap();
        map_positionally(before_last, after_last, &mut diff);

        solve(&before, &after, &node_cache, &mut diff);

        assert!(
            !diff.mapping.contains_key(&(before_fn.id(), after_fn.id())),
            "functions with mostly-different bodies should not be paired by bottom-up expansion"
        );
    }

    /// Maps two nodes (and, recursively, every descendant pair at the same position) as
    /// `Identical`, unconditionally - a test-only stand-in for "some earlier pass already matched
    /// this content", not a general-purpose matcher.
    fn map_positionally(
        before_node: tree_sitter::Node,
        after_node: tree_sitter::Node,
        diff: &mut ASTDiff,
    ) {
        use crate::diff::{ASTMapping, ASTMappingOperation};

        diff.add_mapping(
            before_node.id(),
            after_node.id(),
            ASTMapping {
                cost: 0,
                operation: ASTMappingOperation::Identical,
                reason: ASTMappingReason::IdenticalHash,
            },
        );
        let mut before_cursor = before_node.walk();
        let mut after_cursor = after_node.walk();
        let before_children: Vec<_> = before_node.children(&mut before_cursor).collect();
        let after_children: Vec<_> = after_node.children(&mut after_cursor).collect();
        for (b, a) in before_children.into_iter().zip(after_children) {
            map_positionally(b, a, diff);
        }
    }
}
