/*  This file is part of the CodeDiff code diffing tool.
 *
 *  Copyright (C) 2026 Marko Ivankovic
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
use anyhow::Result;

use crate::test;
use crate::test::helper::human_mapping::assert_matches_human_painting_within_limit;
use crate::test::helper::human_mapping::invariants::assert_ground_truth_invariants_with_known_violations;

#[test]
fn mapping() -> Result<()> {
    // Recorded as found, not examined.
    test::helper::human_mapping::assert_matches_human_mapping_within_limit(
        "c-protocolbuffers-protobuf-this-must-be-autogenerated",
        29,
        29,
    )
}

#[test]
fn painting() -> Result<()> {
    assert_matches_human_painting_within_limit(
        "c-protocolbuffers-protobuf-this-must-be-autogenerated",
        4.1,
    )
}

#[test]
fn invariants() -> Result<()> {
    // Invariant 11, both presets: the removed `UPB_DESC` on before row 122 is left unpainted.
    // Invariant 12, both presets: `FeatureSetDefaults_parse` -> `google_protobuf_FeatureSetDefaults_parse`
    // (before row 123, after row 122) is painted on neither side. Invariant 16, three times: that
    // rename is not painted as its differing words `google_protobuf_` under Minimal, nor entire under
    // Full. Invariant 5: Full leaves columns 58..59 of before row 144 unpainted between two painted
    // regions.
    assert_ground_truth_invariants_with_known_violations(
        "c-protocolbuffers-protobuf-this-must-be-autogenerated",
        8,
    )
}
