# The codediff derivation, kept separate from flake.nix so it can be imported directly by anyone
# not using flakes (`pkgs.callPackage ./packaging/nix/package.nix { }`) and so a nixpkgs submission
# has a single file to take.
#
# `src` is a parameter rather than a `fetchFromGitHub` call baked in here: the flake at the repo
# root passes the checkout itself, so `nix build` and `nix run` work on a working tree with no tag
# and no hash. A nixpkgs submission would instead pass a `fetchFromGitHub { ... hash = "sha256-..."; }`
# and swap `cargoLock.lockFile` for a `cargoHash`, since nixpkgs does not carry the lock file.
{
  lib,
  rustPlatform,
  installShellFiles,
  src ? ../..,
  version ? "0.0.13",
}:

rustPlatform.buildRustPackage {
  pname = "codediff";
  inherit version src;

  # Avoids needing a vendor hash at all: the lock file is right here in the source tree, so Nix
  # can vendor from it directly instead of being told the hash of a vendor directory it has to
  # build first. This is the reason to prefer a flake in-repo over a nixpkgs-style `cargoHash`.
  cargoLock.lockFile = "${src}/Cargo.lock";

  nativeBuildInputs = [ installShellFiles ];

  # Every tree-sitter grammar is compiled from C. stdenv already supplies the compiler, so there is
  # nothing to add here - but it is why this build is slower than the Rust dependency count alone
  # suggests, and it compounds with the release profile's `lto = "fat"` + `codegen-units = 1`
  # (see Cargo.toml). Expect minutes.

  # Default features only (`tui`), the product binary. `stats`/`test-fixtures` gate
  # dataset-analysis dev tools needing git2 (OpenSSL, libssh2) and a bundled SQLite; they are not
  # part of the shipped product, so they are deliberately not exposed as a Nix option.
  cargoBuildFlags = [ "--bin" "codediff" ];

  # --lib only. The fixture-corpus tests are upstream's accuracy benchmark: they need the
  # `test-fixtures` feature and substantial time and memory, which is not what a packaging sanity
  # check is for. (They are also absent entirely if `src` is ever pointed at the crates.io tarball,
  # whose `exclude` list drops tests/ and src/test/data/.)
  cargoTestFlags = [ "--lib" ];

  postInstall = ''
    # Generated by the binary just built, from the same clap definition as --help. This is a
    # native-build assumption: under cross-compilation $out/bin/codediff cannot be executed here
    # and these would have to come from a host build instead.
    installManPage <($out/bin/codediff util man)
    installShellCompletion --cmd codediff \
      --bash <($out/bin/codediff util completions bash) \
      --zsh <($out/bin/codediff util completions zsh) \
      --fish <($out/bin/codediff util completions fish)
  '';

  meta = {
    description = "Fast, robust, syntax-aware code diffing using tree-sitter ASTs";
    longDescription = ''
      CodeDiff parses both sides of a diff with tree-sitter and matches their syntax trees, so a
      change is reported as what it structurally is - an insertion, deletion, update, or move -
      rather than as whichever lines happened to align. It runs as an interactive terminal UI, a
      plain-text batch formatter, or a JSON emitter for editor integrations, and works as a git
      difftool backend and a Jujutsu (jj) diff formatter.
    '';
    homepage = "https://github.com/ivankovic/codediff";
    changelog = "https://github.com/ivankovic/codediff/releases";
    license = lib.licenses.agpl3Plus;
    mainProgram = "codediff";
    maintainers = [ ];
    platforms = lib.platforms.unix ++ lib.platforms.windows;
  };
}
